config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :api do 
    resources :wishlists, only: [:create, :destroy]
  end

  resources :properties, only: [:show] do
    resources :bookings, only: [:new]
  end

  resources :booking_payments, only: [:create]

  get "booking_payments/success", to: "booking_payments#success"

  resources :wishlists, only: [:index]

  resource :profile, only: [:edit, :update]

  resource :email, only: [:edit, :update]
  
  resource :password, only: [:edit, :update]

  resources :reservations, only: [:index] do
    resources :reviews, only: [:new, :create]
  end 

  namespace :owner do
    resources :dashboard, only: :index
    resources :properties
    resources :reservations, only: :index
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :checkin_date, presence: :true
  validates :checkout_date, presence: :true

  has_one :payment
  has_one :review

  scope :upcoming_reservations, -> { where("checkin_date > ?", Date.today).order(:checkin_date) }
  scope :current_reservations, -> { where("checkout_date > ?", Date.today).where("checkin_date < ?", Date.today).order(:checkout_date) }

end

app/controllers/owner/dashboard_controller.rb
module Owner
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end
  end
end

app/controllers/owner/properties_controller.rb
module Owner
  class PropertiesController < ApplicationController
    before_action :authenticate_user!
    def index
      @properties = current_user.properties
    end
  end
end

app/controllers/owner/reservations_controller.rb
module Owner
  class ReservationsController < ApplicationController
    before_action :authenticate_user!
    def index
        @reservations = current_user.properties.map(&:reservations).flatten
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!
    def index 
        @reservations = current_user.reservations
    end
end

app/views/owner/reservations/index.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>

  <main class="px-8 lg:flex-auto my-8">
    <div>
      <h2 class="text-2xl font-semibold leading-7 text-gray-900">Reservations & Payments</h2>
    </div>

    <div class="flex flex-col">
      <% @reservations.each do |reservation| %>
      <div class="mt-4 border border-gray-300 rounded-xl p-6 h-min">
        <div class="flex justify-between">
          <div class="flex items-center">
            <%= image_tag reservation.property.images[0], class:"w-24 h-24 object-cover rounded-md"%>
              <div class="ml-3 text-black font-medium">
                <div class="font-medium text-lg"><%= reservation.property.name %> - <%= reservation.property.city %>, <%= country_name(reservation.property.country_code) %></div>
                  <p class="font-light text-gray-700">Room in the Guest House</p>
                    <span class="inline-flex items-center pointer-events-none block text-sm font-normal text-black">
                      <svg class="mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 12px; width: 12px; fill: currentcolor;">
                      <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
                      </svg>
                      <% if reservation.property.reviews_count > 0 %>
                        <%= reservation.property.average_final_rating.round(2) %> (<%= reservation.property.reviews_count %> reviews)
                      <% else %>
                        New
                      <% end %>
                    </span>
                  </div>
                </div>
                <% if reservation.review.present? %>
                  <span class="inline-flex items-center pointer-events-none block text-md font-semibold text-black text-2xl">
                    <svg class="mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 16px; width: 16px; fill: currentcolor;">
                    <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
                    </svg>
                    <%= reservation.property.average_final_rating.round(2) %>
                  </span>
                <% else  %>
                  <%= link_to 'Add Review', new_reservation_review_path(reservation), class:" flex h-10 mt-2 items-center justify-center rounded-md border border-transparent bg-primary px-8 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"  %>
                <% end %>
          </div>

        <div class="mt-2 border-t border-gray-300">
          <h3 class="text-2xl mt-6 font-medium leading-6 text-gray-900 ">Trip Details</h3>
            <div class="flex justify-between font-normal mt-4">
              <p>Dates</p>
              <p class="font-normal">
                <%= reservation.checkin_date.strftime("%d, %b") %> - 
                <%= reservation.checkout_date.strftime("%d, %b %Y") %>
              </p>              
            </div>
            <div class="flex justify-between font-normal mt-2">
              <p class=" underline">Guests</p>
              <p class="font-semibold">2 Guests</p>
            </div>
        </div>

        <div class="relative mt-2 mb-10">
          <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
        </div>

        <div>
          <h3 class="text-2xl mt-6 font-medium leading-6 text-gray-900 ">Price Details</h3>
          <div class="flex justify-between font-light mt-4">
            <p><%= humanized_money_with_symbol(reservation.property.price) %> X <%= (reservation.checkout_date - reservation.checkin_date).to_i %></span> night</p>
              <p><%= currency_symbol %><%= reservation.payment.base_fare %></span></p>
          </div>
          <div class="flex justify-between mt-2">
            <p class="underline">Airbnb Service Fee</p>
            <p> <%= currency_symbol %> <%= reservation.payment.service_fee %></span></p>
          </div>
          </div>

          <div class="relative py-2">
            <div class="absolute inset-0 flex items-center" aria-hidden="true">
              <div class="w-full border-t border-gray-300"> </div>
            </div>
          </div>

          <div class="flex justify-between mt-2">
            <p class="font-bold">Total</p>
            <p class="font-bold"><%= humanized_money_with_symbol(reservation.payment.total_amount) %></p>
          </div>
        </div>
      <% end %>
    </div>        
  </main>
</div>