config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :api do 
    resources :wishlists, only: [:create, :destroy]
  end

  resources :properties, only: [:show] do
    resources :bookings, only: [:new]
  end

  resources :booking_payments, only: [:create]

  get "booking_payments/success", to: "booking_payments#success"

  resources :wishlists, only: [:index]

  resource :profile, only: [:edit, :update]

  resource :email, only: [:edit, :update]
  
  resource :password, only: [:edit, :update]

  resources :reservations, only: [:index] do
    resources :reviews, only: [:new, :create]
  end 

  namespace :owner do
    resources :dashboard, only: :index
    resources :properties
    resources :reservations, only: :index
  end
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: :true
  validates :headline, presence: :true
  validates :description, presence: :true
  validates :address_1, presence: :true
  validates :city, presence: :true
  validates :state, presence: :true
  validates :country_code, presence: :true

  monetize :price_cents, allow_nil: true

  has_many_attached :images

  has_many :reviews, dependent: :destroy

  has_many :property_amenities, dependent: :destroy
  has_many :amenities, through: :property_amenities, source: :amenity, dependent: :destroy

  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_users, through: :wishlists, source: :user, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :users, dependent: :destroy

  has_many :payments, through: :reservations, dependent: :destroy

  has_rich_text :description

  def update_average_rating
    average_rating = reviews.average(:final_rating);
    update_column(:average_final_rating, average_rating)
  end

  def average_cleanliness_rating
    reviews.average(:cleanliness_rating)
  end

  def average_accuracy_rating
    reviews.average(:accuracy_rating)
  end

  def average_checkin_rating
    reviews.average(:checkin_rating)
  end

  def average_communication_rating
    reviews.average(:communication_rating)
  end

  def average_location_rating
    reviews.average(:location_rating)
  end

  def average_value_rating
    reviews.average(:value_rating)
  end

  def wishlisted_by?(user = nil)
    return if user.nil?

    wishlisted_users.include?(user)
  end

  def available_dates
    next_reservation = reservations.upcoming_reservations.first
    current_reservation = reservations.current_reservations.first

    if current_reservation.nil? && next_reservation.nil?
      Date.tomorrow.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')

    elsif current_reservation.nil?
      Date.tomorrow.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')

    elsif next_reservation.nil?
      current_reservation.checkout_date.strftime('%e %b')..(Date.tomorrow + 30.days).strftime('%e %b')

    else 
      current_reservation.checkout_date.strftime('%e %b')..next_reservation.checkin_date.strftime('%e %b')
    end
  end
end

app/controllers/owner/dashboard_controller.rb
module Owner
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end
  end
end

app/controllers/owner/properties_controller.rb
module Owner
  class PropertiesController < ApplicationController
    before_action :authenticate_user!
    def index
      @properties = current_user.properties
    end
  end
end

app/controllers/owner/reservations_controller.rb
module Owner
  class ReservationsController < ApplicationController
    before_action :authenticate_user!
    def index
        @reservations = current_user.properties.map(&:reservations).flatten
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    def show
        @property = Property.includes(:reviews).find(params[:id])
        @overall_rating_counts = @property
                                    .reviews
                                    .group('ROUND(final_rating)')
                                    .count
                                    .transform_keys(&:to_i)
        @overall_rating_counts.default = 0

        upcoming_reservations = @property.reservations.upcoming_reservations.pluck(:checkin_date, :checkout_date)
        @blocked_dates = upcoming_reservations.map{|reservation| [reservation[0].to_s, (reservation[1] - 1.day).to_s]}
        
    end
end

app/views/owner/properties/edit.html.erb
<h1>Edit Property</h1>

app/views/owner/properties/index.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">

  <%= render 'shared/owner_sidebar' %>

  <main class="px-8 py-8 border rounded-md lg:flex-auto my-8">

    <div>
      <div class="flex justify-between">
        <h2 class="text-2xl font-semibold leading-7 text-gray-900">Properties</h2>
        <%= link_to "Add Property", new_owner_property_path, class:"cursor-pointer mt-4 flex items-center justify-center rounded-md border border-transparent bg-primary px-6 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>

      </div>
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
        <% @properties.each do |property| %>
        <div class="flex flex-col">
          <%= render 'properties/property_item', property: property, minimal_details: false %>
          <%= link_to "Edit Property", edit_owner_property_path(property), class:"cursor-pointer mt-4 flex items-center justify-center rounded-md border-2 border-primary text-primary bg-white px-6 py-2 text-base font-medium hover:bg-primary hover:text-white focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
        </div>
        <%end%>
      </div>
    </div>
  </main>
</div>

app/views/owner/properties/new.html.erb
<h1>Add Property</h1>